---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  # workaround for https://github.com/saltstack/salt-bootstrap/issues/632
  # python-requests : Depends: python-urllib3 (>= 1.7.1) but it is not installable
  salt_bootstrap_url: https://bootstrap.saltstack.com/develop
  salt_bootstrap_options: -P
  formula: beaver
  state_top:
    base:
      '*':
        - beaver
        - beaver.ppa

platforms:
  - name: ubuntu-12.04
    # t1.micro, Ubuntu 12.04,
    image_id: ami-e893299b

suites:
  - name: default

  - name: tcp-output
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - beaver
        beaver.sls:
          beaver:
            transport: tcp

  - name: json-out
    provisioner:
      pillars-from-files:
        beaver.sls: pillar.example
      pillars:
        top.sls:
          base:
            '*':
              - beaver

# - name: dependencies
#    provisioner:
#      # workaround for https://github.com/saltstack/salt-bootstrap/issues/632
#      # python-requests : Depends: python-urllib3 (>= 1.7.1) but it is not installable
#      salt_bootstrap_url: https://bootstrap.saltstack.com/develop
#      salt_bootstrap_options: -P
#      dependencies:
#        - name: elasticsearch
#          path: ../elasticsearch-formula

#  - name: vendor_path
#    provisioner:
#      vendor_path: ../sample-vendor-path

# TODO: Move to a light weight rspec test
#  - name: bad_vendor_path
#    provisioner:
#      vendor_path: ../missing-sample-vendor-path
